### ISSUE TITLE
🚀 : Update package.name with 'tech.newchapter.langx',

### ISSUE THREAD

**Issue by xuelink** [langx/langx-flutter#1]
**Is your feature request related to a problem? Please describe.**
Yes. The current package name is not descriptive enough and does not reflect the technological advancement and innovative nature of the product.  A more fitting and memorable name is needed to enhance brand recognition and better communicate the purpose of the language model.

**Describe the solution you'd like**
Update the package name to 'tech.newchapter.langx'. This new name is concise, relevant to the language model domain, and hints at the cutting-edge technology behind it.

'tech.newchapter.langx' was deemed the most suitable due to its clarity, memorability, and relevance to the product's positioning.

**Additional context**
This change is primarily aimed at improving brand perception and making the package name more aligned with the product's identity. We believe this minor adjustment can have a significant positive impact on user engagement and overall product success.

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by DH-555** [comment]
Solved: https://github.com/langx/langx-flutter/commit/41820b21a6842d4514c9224a47c29bfc0cdc813d
