### ISSUE TITLE
🚀 : Update Readme w/ Issues, Contributing, Stargazers, Contributors, License

### ISSUE THREAD

**Issue by xuelink** [langx/langx-flutter#10]
Similar to: https://github.com/langx/token-website/issues/2

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
@binbang12 Can you please update readme here as well that you did it w/ previous PR : https://github.com/langx/token-website/pull/10

**Comment by Caluryth** [comment]
> @binbang12 Can you please update readme here as well that you did it w/ previous PR : [langx/token-website#10](https://github.com/langx/token-website/pull/10)

Sure @xuelink!
