### ISSUE TITLE
🚀 : Community Section 

### ISSUE THREAD

**Issue by xuelink** [langx/langx-flutter#13]
Make cards to get users and show on the UI. Not clickable for now just UI user cards.

- [x] UI #14 
- [x] DB connection #26 

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
Dark theme seems little problematic due to theme options i guess.

<img width="452" alt="Screenshot 2024-06-20 at 12 58 53 AM" src="https://github.com/langx/langx-flutter/assets/3280475/d8872e4b-20ca-4344-96ee-4f19018c0889">

We also have to impelement grid system for larger screens, tablets/web apps. I did here in angular side: 

https://github.com/langx/langx/blob/602dd0b7bb846efe38be4a707131d16ee680be7f/src/app/components/home/new/new.component.html#L7-L25 

We can copy the same grid system no problem.

<img width="1799" alt="Screenshot 2024-06-20 at 1 01 42 AM" src="https://github.com/langx/langx-flutter/assets/3280475/c5d9c945-20fa-4238-854f-3deba3961648">

**Comment by DH-555** [comment]
I will make the db connection

**Comment by xuelink** [comment]
I also implemented here w/ f136a1f

https://github.com/langx/langx-flutter/assets/3280475/11470675-13e9-4248-b4ca-2ebd211342b8

**Comment by xuelink** [comment]
> I will make the db connection

Ok, then i leave it to you :)

**Comment by xuelink** [comment]
@DH-555 to help you, i use these querries to get sections seperately.

https://github.com/langx/langx/blob/602dd0b7bb846efe38be4a707131d16ee680be7f/src/app/services/user/user.service.ts#L106C1-L221C1
