### ISSUE TITLE
🚀 : Update the name of the project to `langx-flutter` instead of `langx_flutter`

### ISSUE THREAD

**Issue by xuelink** [langx/langx-flutter#2]
**Is your feature request related to a problem? Please describe.**
Yes. While not a critical issue, the current project name (`langx_flutter`) uses an underscore, which deviates from common naming conventions in the Flutter ecosystem.  Most Flutter projects use hyphens to separate words in project names.

**Describe the solution you'd like**
Update the project name to `langx-flutter`, replacing the underscore with a hyphen. This change aligns the project's naming with standard Flutter practices, making it more recognizable and easier to integrate with other Flutter projects.

**Describe alternatives you've considered**
We considered leaving the project name as is, as the underscore doesn't impact functionality. However, for consistency and better integration with the broader Flutter community, we decided that adopting the hyphen convention is the preferred approach.

**Additional context**
This change is purely cosmetic and aims to improve the project's adherence to Flutter naming conventions. It will not affect the project's code or functionality, but it will make it more consistent with other Flutter projects.

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by DH-555** [comment]
It's not possible: https://dart.dev/tools/linter-rules/package_names

**Comment by DH-555** [comment]
Closing as changing it to that value throws an error
