### ISSUE TITLE
🚀 : Implement Font `Comfortaa` by Google Fonts

### ISSUE THREAD

**Issue by xuelink** [langx/langx-flutter#4]
**Feature Request: Implement Font `Comfortaa` by Google Fonts**

**Is your feature request related to a problem? Please describe.**
I am looking to enhance the aesthetic appeal of my application by integrating a modern and clean font. The current font does not align with the design vision I have for the application, leading to a somewhat outdated and inconsistent look.

**Describe the solution you'd like**
I would like to implement the `Comfortaa` font from Google Fonts throughout the application. This would involve:
1. Importing the `Comfortaa` font into the project.
2. Updating the CSS styles to use `Comfortaa` as the primary font family.
3. Ensuring that all text elements within the application reflect this change for a consistent and cohesive design.

**Describe alternatives you've considered**
I have considered other fonts such as `Roboto` and `Open Sans`, but they do not match the unique, rounded aesthetic that `Comfortaa` offers. Additionally, custom fonts were considered but would require more resources to develop and integrate compared to using a readily available Google Font.

**Additional context**
Here is a link to the Google Fonts page for `Comfortaa`: [Comfortaa on Google Fonts](https://fonts.google.com/specimen/Comfortaa).

To import `Comfortaa`, the following link can be added to the HTML:
```html
<link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&display=swap" rel="stylesheet">
```

CSS example:
```css
body {
    font-family: 'Comfortaa', cursive;
}
```

_If you want to speed up the process of this issue, please send 🚀 as a reaction._
_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by DH-555** [comment]
We don't use CSS here 👀 

Doing it right now

**Comment by xuelink** [comment]
> We don't use CSS here 👀
> 
> Doing it right now

Awesome, you can also use [Backlog](https://backlog.langx.io) if you want

**Comment by DH-555** [comment]
https://github.com/langx/langx-flutter/pull/6
